version: '3.7'

services:
 api:
  image: node:12.22.4
  env_file:
   - .env
  command: bash -c "yarn typeorm migration:run && yarn dev:server"
  depends_on:
   - postgres
  ports:
   - 3333:3333
  volumes:
   - ./:/app
  working_dir: /app
  networks:
   - default

 postgres:
  image: postgres:13.4
  environment:
   POSTGRES_PASSWORD: docker
   POSTGRES_USER: postgres
   POSTGRES_DB: temchurras
  volumes:
   - ./pgdata:/var/lib/postgresql/data
  ports:
   - 5432:5432
  networks:
   - default

networks:
 default:
